/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class DELETEEVENTMANAGER1 extends javax.swing.JFrame {

    /**
     * Creates new form DELETEEVENTMANAGER1
     */
    public DELETEEVENTMANAGER1() {
        initComponents();
    }
    public String date;
    public DELETEEVENTMANAGER1(String a) {
        initComponents();
         date=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        timelist = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/delete1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 42, 40));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("DELETION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 20, 144, -1));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 78, 145, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/calendar1.png"))); // NOI18N
        jLabel2.setText("DATE :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 30));

        timelist.setOpaque(false);
        timelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timelistActionPerformed(evt);
            }
        });
        getContentPane().add(timelist, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 116, 174, 23));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clock1.png"))); // NOI18N
        jLabel8.setText("START TIME :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 116, 147, -1));

        delete.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 0, 51));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/trash.png"))); // NOI18N
        delete.setText("DELETE");
        delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delete.setOpaque(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 151, 117, 44));

        back.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/left-arrow.png"))); // NOI18N
        back.setOpaque(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 43, 19));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/DELETEEVENTBACK.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timelistActionPerformed
      
    }//GEN-LAST:event_timelistActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      if(timelist.getItemCount()!=0)
     { String time=timelist.getSelectedItem().toString();
       int result = JOptionPane.showConfirmDialog(null,"Sure? You want to DELETE?", "",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION)
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject1","root","123456");
            Statement stmt=con.createStatement();
             
            String query = "DELETE FROM eventmanager WHERE date="+"\""+date+"\""+"&& starttime="+"\""+time+"\""+";";
            stmt.executeUpdate(query);
            stmt.close();
            con.close();
            System.out.println("Success");
        } catch (Exception ex) {
            Logger.getLogger(DELETEEVENTMANAGER.class.getName()).log(Level.SEVERE, null, ex);
        }
        timelist.removeAllItems();
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject1","root","123456");
             Statement stmt=con.createStatement();
                      String s="select starttime from eventmanager where date="+"\""+date+"\""+";";
                      ResultSet rs=stmt.executeQuery(s);
                       while(rs.next())
                      {
                      String time1=rs.getString(1);                    
                      timelist.addItem(time1);
                      }
                      rs.close();con.close();stmt.close();
                      
        } catch (Exception ex) {
            Logger.getLogger(MODIFYEVENTMANAGER.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    else
      {  JOptionPane.showMessageDialog(null, "NO EVENT ON THIS PARTICULAR DATE");
      dispose();
       new DELETEEVENTMANAGER().setVisible(true);
      }
      
    }//GEN-LAST:event_deleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       jTextField1.setText(""+date);
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject1","root","123456");
             Statement stmt=con.createStatement();
                      String s="select starttime from eventmanager where date="+"\""+date+"\""+";";
                      ResultSet rs=stmt.executeQuery(s);
                       while(rs.next())
                      {
                      String time=rs.getString(1);                    
                      timelist.addItem(time);
                      }
                      rs.close();con.close();stmt.close();
                      
        } catch (Exception ex) {
            Logger.getLogger(MODIFYEVENTMANAGER.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(timelist.getItemCount() == 0)
        {
                     JOptionPane.showMessageDialog(null, "NO EVENT ON THIS PARTICULAR DATE");
           dispose();
           new DELETEEVENTMANAGER().setVisible(true);
           
        } 
    }//GEN-LAST:event_formWindowOpened

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new DELETEEVENTMANAGER().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELETEEVENTMANAGER1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELETEEVENTMANAGER1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELETEEVENTMANAGER1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELETEEVENTMANAGER1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELETEEVENTMANAGER1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> timelist;
    // End of variables declaration//GEN-END:variables
}
