/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.*;

/**
 *
 * @author admin
 */
public class NEWDIARYENTRY extends javax.swing.JFrame {

    /**
     * Creates new form NEWDIARYENTRY
     */
    public NEWDIARYENTRY() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        entry = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        place = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        time123 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        happyrdb = new javax.swing.JRadioButton();
        avgrdb = new javax.swing.JRadioButton();
        sadrdb = new javax.swing.JRadioButton();
        enter = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        date123 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, 325, 47));

        entry.setColumns(20);
        entry.setRows(5);
        jScrollPane1.setViewportView(entry);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 567, 168));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/school.png"))); // NOI18N
        jLabel2.setText("ENTRY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 79, 29));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/map.png"))); // NOI18N
        jLabel3.setText("PLACE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 273, 116, -1));
        getContentPane().add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 275, 114, 26));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/calendar1.png"))); // NOI18N
        jLabel4.setText("DATE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 311, 68, -1));

        time.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clock.png"))); // NOI18N
        time.setText("TIME");
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 311, 63, 26));
        getContentPane().add(time123, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 313, 114, -1));

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/satisfaction.png"))); // NOI18N
        jLabel6.setText("MOOD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 349, -1, -1));

        happyrdb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(happyrdb);
        happyrdb.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        happyrdb.setForeground(new java.awt.Color(255, 255, 255));
        happyrdb.setSelected(true);
        happyrdb.setText("HAPPY");
        happyrdb.setFocusPainted(false);
        happyrdb.setOpaque(false);
        getContentPane().add(happyrdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        buttonGroup1.add(avgrdb);
        avgrdb.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        avgrdb.setForeground(new java.awt.Color(255, 255, 255));
        avgrdb.setText("AVERAGE");
        avgrdb.setOpaque(false);
        getContentPane().add(avgrdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        buttonGroup1.add(sadrdb);
        sadrdb.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        sadrdb.setForeground(new java.awt.Color(255, 255, 255));
        sadrdb.setText("SAD");
        sadrdb.setOpaque(false);
        getContentPane().add(sadrdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        enter.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        enter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/add-anchor-point.png"))); // NOI18N
        enter.setText("ENTER");
        enter.setOpaque(false);
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 392, 125, 42));

        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("✖\t");
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 450, -1, 19));

        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/real-estate.png"))); // NOI18N
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 450, -1, 19));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/left-arrow.png"))); // NOI18N
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 450, -1, 19));

        date123.setOpaque(false);
        getContentPane().add(date123, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 317, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/create-new-pencil-button.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 62, 47));

        clear.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clear.png"))); // NOI18N
        clear.setText("CLEAR");
        clear.setOpaque(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 371, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clock1.png"))); // NOI18N
        jButton1.setToolTipText("CLICK TO GET CURRENT TIME");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 311, 25, 26));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/newback.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  int result = JOptionPane.showConfirmDialog(null,"CLOSE?", "",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION)
            
      dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
new WELCOME().setVisible(true);
dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        DateFormat df=new SimpleDateFormat("yyyy-MM-dd");  
            
            if(entry.getText().equals(""))
            JOptionPane.showMessageDialog(null,"ENTER FIELD EMPTY ");
              else if(place.getText().equals(""))
            JOptionPane.showMessageDialog(null,"PLACE FIELD EMPTY ");
              else if(time123.getText().equals(""))
            JOptionPane.showMessageDialog(null,"TIME FIELD EMPTY ");
              else if(date123.getDate().equals(""))
            JOptionPane.showMessageDialog(null,"DATE NOT SPECIFIED");
             
              else{
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject1","root","123456");
            Statement stmt=con.createStatement();
            String entry1=entry.getText();
            String place1=place.getText();
            String time=time123.getText();
            String date1 = df.format(date123.getDate());
            String z = null;
            if(happyrdb.isSelected()==true)
                z="Happy";
            else if(avgrdb.isSelected()==true)
                z="Average";
            else if(sadrdb.isSelected()==true)
                z="Sad";
            String query = "Insert into diaryentry1 values("+"\""+entry1+"\""+","+"\""+place1+"\""+","+"\""+date1+"\""+","+"\""+time+"\""+","+"\""+z+"\""+");";
            
            stmt.executeUpdate(query);
            stmt.close();
            con.close();
          JOptionPane.showMessageDialog(null,"ENTRY ADDED!");
                entry.setText("");
           place.setText("");
           time123.setText("");
           happyrdb.setSelected(false);
           avgrdb.setSelected(false);
           sadrdb.setSelected(false);
            
            
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,"Unsupported Character(s) inserted! or other logical error!");
                
        }   }  
            
            
    }//GEN-LAST:event_enterActionPerformed
                                                             
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new DIARYENTRYMAIN().setVisible(true);
         dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     Date date= new Date();
     DateFormat df=new SimpleDateFormat("yyyy-MM-dd");   
     date123.setDate(date);
     Calendar cal = Calendar.getInstance(); 
cal.getTime(); 
SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss"); 
time123.setText(sdf.format(cal.getTime()));
     
    }//GEN-LAST:event_formWindowOpened

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
           entry.setText("");
           place.setText("");
           time123.setText("");
           happyrdb.setSelected(false);
           avgrdb.setSelected(false);
           sadrdb.setSelected(false);
           
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Calendar cal = Calendar.getInstance(); 
cal.getTime(); 
SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss"); 
time123.setText(sdf.format(cal.getTime()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEWDIARYENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEWDIARYENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEWDIARYENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEWDIARYENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEWDIARYENTRY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton avgrdb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private com.toedter.calendar.JDateChooser date123;
    private javax.swing.JButton enter;
    private javax.swing.JTextArea entry;
    private javax.swing.JRadioButton happyrdb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField place;
    private javax.swing.JRadioButton sadrdb;
    private javax.swing.JLabel time;
    private javax.swing.JTextField time123;
    // End of variables declaration//GEN-END:variables
}
