/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class NEWEVENTMANAGER extends javax.swing.JFrame {

    /**
     * Creates new form NEWEVENTMANAGER
     */
    public NEWEVENTMANAGER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        event = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        place = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        starttime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        endtime = new javax.swing.JTextField();
        flagrdb = new javax.swing.JRadioButton();
        add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        date123 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText(" PLAN A NEW EVENT ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 20, 370, -1));

        jScrollPane1.setOpaque(false);

        event.setColumns(20);
        event.setRows(5);
        jScrollPane1.setViewportView(event);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 566, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/map.png"))); // NOI18N
        jLabel2.setText("PLACE :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, 143, -1));

        place.setOpaque(false);
        getContentPane().add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 168, 180, 32));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/calendar1.png"))); // NOI18N
        jLabel3.setText("DATE   :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 143, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clock1.png"))); // NOI18N
        jLabel4.setText("START TIME :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 239, 101, 30));

        starttime.setToolTipText("24 hours");
        starttime.setOpaque(false);
        starttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starttimeActionPerformed(evt);
            }
        });
        getContentPane().add(starttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 245, 186, 23));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clock1.png"))); // NOI18N
        jLabel5.setText("END TIME     :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 276, -1, -1));

        endtime.setToolTipText("24 hours");
        endtime.setOpaque(false);
        endtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endtimeActionPerformed(evt);
            }
        });
        getContentPane().add(endtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 275, 186, 24));

        flagrdb.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        flagrdb.setText("FLAG AS IMPORTANT");
        flagrdb.setOpaque(false);
        flagrdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagrdbActionPerformed(evt);
            }
        });
        getContentPane().add(flagrdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 311, -1, 24));

        add.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/add-anchor-point.png"))); // NOI18N
        add.setText("ADD");
        add.setOpaque(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 346, 107, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 393, 282, 46));

        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("✖\t");
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 409, -1, 19));

        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/real-estate.png"))); // NOI18N
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 409, -1, 19));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/left-arrow.png"))); // NOI18N
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 409, -1, 19));

        date123.setOpaque(false);
        getContentPane().add(date123, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 214, 180, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/create-new-pencil-button.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 43, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/red-flag.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 311, 32, -1));

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clear.png"))); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 331, -1, -1));

        jLabel9.setText("(hh:mm:ss && 24hrs format)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 244, 190, 24));

        jLabel10.setText("(hh:mm:ss && 24hrs format)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 275, 190, 24));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/background.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void starttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_starttimeActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       int result = JOptionPane.showConfirmDialog(null,"CLOSE?", "",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION)
            
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         new WELCOME().setVisible(true);
         dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
            DateFormat df=new SimpleDateFormat("yyyy-MM-dd");  
         if(event.getText().equals(""))
            JOptionPane.showMessageDialog(null,"ENTER FIELD EMPTY ");
          else if(place.getText().equals(""))
            JOptionPane.showMessageDialog(null,"PLACE NOT SPECIFIED");
           else if(date123.getDate().equals(""))
            JOptionPane.showMessageDialog(null,"DATE NOT SPECIFIED");
          else if(date123.getDate().equals(""))
            JOptionPane.showMessageDialog(null,"DATE NOT SPECIFIED");
           else if(starttime.getText().equals(""))
            JOptionPane.showMessageDialog(null," START TIME FIELD EMPTY ");
           else if(endtime.getText().equals(""))
            JOptionPane.showMessageDialog(null," END TIME FIELD EMPTY ");
        
        else
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject1","root","123456");
            Statement stmt=con.createStatement();

            String date1 = df.format(date123.getDate());
            String event1=event.getText();
            String place1=place.getText();
            String starttime1=starttime.getText();
             String endtime1=endtime.getText();
            String a = null;
            if(flagrdb.isSelected()==true)
                 a="Yes";
            else
                a="No";
            String query = "Insert into eventmanager values("+"\""+event1+"\""+","+"\""+date1+"\""+","+"\""+place1+"\""+","+"\""+starttime1+"\""+","+"\""+endtime1+"\""+","+"\""+a+"\""+");";
            stmt.executeUpdate(query);
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"ENTRY ADDED!");
             event.setText("");
           place.setText("");
           starttime.setText("");
           endtime.setText("");
           flagrdb.setSelected(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"UNSUPPORTED CHARACTER FORMAT OR UNIDENTIFIED LOGICAL ERROR!");
        }
        
    }//GEN-LAST:event_addActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       new EVENTMANAGERMAIN().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           Date date= new Date(); 
     DateFormat df=new SimpleDateFormat("yyyy-MM-dd");   
     date123.setDate(date);
    }//GEN-LAST:event_formWindowOpened

    private void flagrdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagrdbActionPerformed
        
         
    }//GEN-LAST:event_flagrdbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        event.setText("");
           place.setText("");
           starttime.setText("");
           endtime.setText("");
           flagrdb.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void endtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endtimeActionPerformed
        
        
    }//GEN-LAST:event_endtimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEWEVENTMANAGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEWEVENTMANAGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEWEVENTMANAGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEWEVENTMANAGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEWEVENTMANAGER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private com.toedter.calendar.JDateChooser date123;
    private javax.swing.JTextField endtime;
    private javax.swing.JTextArea event;
    private javax.swing.JRadioButton flagrdb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField place;
    private javax.swing.JTextField starttime;
    // End of variables declaration//GEN-END:variables
}
