/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class SEARCHDIARYENTRY extends javax.swing.JFrame {

    /**
     * Creates new form SEARCHDIARYENTRY
     */
    public SEARCHDIARYENTRY() {
        initComponents();}
    public String date;
    public SEARCHDIARYENTRY(String a) {
        initComponents();
        date=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        placetf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        timetf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        happyrdb = new javax.swing.JRadioButton();
        avgrdb = new javax.swing.JRadioButton();
        sadrdb = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel1.setText("RESULTS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 181, -1));

        jScrollPane1.setOpaque(false);

        resultta.setEditable(false);
        resultta.setColumns(20);
        resultta.setRows(5);
        resultta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(resultta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 528, 181));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/map.png"))); // NOI18N
        jLabel2.setText("PLACE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 168, 31));

        placetf.setEditable(false);
        placetf.setOpaque(false);
        getContentPane().add(placetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 250, 144, 26));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clock.png"))); // NOI18N
        jLabel3.setText("TIME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 293, 114, -1));

        timetf.setEditable(false);
        timetf.setToolTipText("24 hours");
        timetf.setOpaque(false);
        getContentPane().add(timetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 292, 144, 24));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/satisfaction.png"))); // NOI18N
        jLabel4.setText("MOOD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, 114, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 316, 120, 54));

        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("✖\t");
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 405, -1, 19));

        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/real-estate.png"))); // NOI18N
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 405, -1, 19));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/left-arrow.png"))); // NOI18N
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 405, -1, 19));

        buttonGroup1.add(happyrdb);
        happyrdb.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        happyrdb.setText("HAPPY");
        happyrdb.setEnabled(false);
        happyrdb.setOpaque(false);
        getContentPane().add(happyrdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 334, -1, -1));

        buttonGroup1.add(avgrdb);
        avgrdb.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        avgrdb.setText("AVERAGE");
        avgrdb.setEnabled(false);
        avgrdb.setOpaque(false);
        getContentPane().add(avgrdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 334, -1, -1));

        buttonGroup1.add(sadrdb);
        sadrdb.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        sadrdb.setText("SAD");
        sadrdb.setEnabled(false);
        sadrdb.setOpaque(false);
        getContentPane().add(sadrdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 334, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/analysis.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       int result = JOptionPane.showConfirmDialog(null,"CLOSE?", "",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION)
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new DIARYENTRYMAIN().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new SEARCHDIARYENTRY1().setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Class.forName("java.sql.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject1","root","123456");
            Statement stmt=con.createStatement();
            String s="Select * from diaryentry1 where date="+"\""+date+"\""+";";
            ResultSet rs=stmt.executeQuery(s);
            while(rs.next())
            {
                String entry1=rs.getString("entry");
                String place=rs.getString("place");
                String date11=rs.getString("date");
                String time=rs.getString("time");
                String mood=rs.getString("mood");
                resultta.setText(""+entry1);
                placetf.setText(""+place);
                timetf.setText(""+time);
                if(mood.equals("Average"))
                    avgrdb.setSelected(true);
                 if(mood.equals("Sad"))
                    sadrdb.setSelected(true);
                 if(mood.equals("Happy"))
                happyrdb.setSelected(true);
                          
          }
            con.close();
            rs.close();
            stmt.close();
            if(resultta.getText().equals(""))
                 {
                     JOptionPane.showMessageDialog(null, "NO ENTRIES !");
                     dispose();
                      new SEARCHDIARYENTRY1().setVisible(true);
                 }
        } catch (Exception ex) {
            Logger.getLogger(SEARCHDIARYENTRY.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEARCHDIARYENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEARCHDIARYENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEARCHDIARYENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEARCHDIARYENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEARCHDIARYENTRY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton avgrdb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton happyrdb;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField placetf;
    private javax.swing.JTextArea resultta;
    private javax.swing.JRadioButton sadrdb;
    private javax.swing.JTextField timetf;
    // End of variables declaration//GEN-END:variables
}
