/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class UPCOMINGEVENT extends javax.swing.JFrame {

    /**
     * Creates new form UPCOMINGEVENT
     */
  
    public UPCOMINGEVENT() {
        initComponents();
        
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timelist = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        endtf = new javax.swing.JTextField();
        important1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultta = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        placetf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        datelist = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/flag.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 43, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clock1.png"))); // NOI18N
        jLabel3.setText("START TIME:(24hrs)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 150, -1));

        timelist.setOpaque(false);
        timelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timelistActionPerformed(evt);
            }
        });
        getContentPane().add(timelist, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 222, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/clock1.png"))); // NOI18N
        jLabel4.setText("END TIME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 92, -1));

        endtf.setEditable(false);
        endtf.setToolTipText("24 hours");
        getContentPane().add(endtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 152, 24));

        important1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        important1.setForeground(new java.awt.Color(255, 255, 255));
        important1.setText("FLAGGED AS IMPORTANT");
        important1.setContentAreaFilled(false);
        important1.setEnabled(false);
        important1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                important1ActionPerformed(evt);
            }
        });
        getContentPane().add(important1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 24));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESULTS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, 149, 47));

        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("✖\t");
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, 19));

        jScrollPane1.setOpaque(false);

        resultta.setEditable(false);
        resultta.setColumns(20);
        resultta.setRows(5);
        jScrollPane1.setViewportView(resultta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 670, 119));

        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/real-estate.png"))); // NOI18N
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, 19));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/left-arrow.png"))); // NOI18N
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, 19));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/map.png"))); // NOI18N
        jLabel2.setText("PLACE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 194, 93, 29));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/analysis.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 62, 47));

        placetf.setEditable(false);
        getContentPane().add(placetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 159, 25));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/calendar1.png"))); // NOI18N
        jLabel10.setText("DATE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 70, 30));

        datelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datelistActionPerformed(evt);
            }
        });
        getContentPane().add(datelist, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 137, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip/project/variousbackground3.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Class.forName("java.sql.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject1","root","123456");
             Statement stmt=con.createStatement();
             String s="select  distinct date from eventmanager where date>=curdate() order by date;";
             ResultSet rs=stmt.executeQuery(s);
             datelist.removeAllItems();
             timelist.removeAllItems();
             while(rs.next())
                      {
                      String date=rs.getString(1);                    
                      datelist.addItem(date);
                      }
                      rs.close();con.close();stmt.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
       if(resultta.getText().equals(""))
       {
          JOptionPane.showMessageDialog(this,"NO UPCOMING EVENTS!");
          new EVENTMANAGERMAIN().setVisible(true);
          dispose();
          
       }
           
       

    }//GEN-LAST:event_formWindowOpened

    private void timelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timelistActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject1","root","123456");
            Statement stmt=con.createStatement();
            String time=timelist.getSelectedItem().toString();
            String date=datelist.getSelectedItem().toString();
            String s="select * from eventmanager where date="+"\""+date+"\""+" && starttime="+"\""+time+"\""+" order by starttime;";
            ResultSet rs=stmt.executeQuery(s);
            
            while(rs.next())
            {
                String event=rs.getString("event");
                String place=rs.getString("place");
                String endtime=rs.getString("endtime");
                String impor=rs.getString("important");
                resultta.setText(""+event);
                placetf.setText(""+place);
                
                endtf.setText(""+endtime);
                if(impor.equals("Yes"))
                important1.setSelected(true);
                else
                important1.setSelected(false);
            }
            con.close();
            rs.close();
            stmt.close();
        } catch (Exception ex) {
            
        }
        
        
    }//GEN-LAST:event_timelistActionPerformed

    private void important1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_important1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_important1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int result = JOptionPane.showConfirmDialog(null,"CLOSE?", "",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION)
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new WELCOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new EVENTMANAGERMAIN().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void datelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datelistActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject1","root","123456");
             Statement stmt=con.createStatement();
             String date=datelist.getSelectedItem().toString();
             timelist.removeAllItems();
             
            
             String s="select starttime from eventmanager where date="+"\""+date+"\""+";";
                      ResultSet rs=stmt.executeQuery(s);
                     
                      
                       while(rs.next())
                      {
                      String time=rs.getString(1);                    
                      timelist.addItem(time);
                      }
                      rs.close();con.close();stmt.close();
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_datelistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPCOMINGEVENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPCOMINGEVENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPCOMINGEVENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPCOMINGEVENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPCOMINGEVENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> datelist;
    private javax.swing.JTextField endtf;
    private javax.swing.JRadioButton important1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField placetf;
    private javax.swing.JTextArea resultta;
    private javax.swing.JComboBox<String> timelist;
    // End of variables declaration//GEN-END:variables
}
